version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: letslink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/letslink?schema=public
      JWT_SECRET: super-secret-key
      PORT: 4000
      CORS_ORIGIN: http://localhost:3000
    ports:
      - '4000:4000'
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/package.json:/app/package.json
    command: sh -c "npx prisma migrate deploy || npx prisma db push; npm run start"
volumes:
  db-data:
